version: '3.8'
services:
  despacho-backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://despacho-mysql:3306/despacho_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=despacho_user
      - SPRING_DATASOURCE_PASSWORD=monsalve1974
    depends_on:
      - despacho-mysql
  despacho-mysql:
    image: mysql:8.0
    container_name: despacho-mysql
    environment:
      MYSQL_DATABASE: despacho_db
      MYSQL_USER: despacho_user
      MYSQL_PASSWORD: monsalve1974
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - despacho_mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  despacho_mysql_data:
